services:
  db:
    image: mysql:8
    volumes:
      - "./.docker/db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - jacalnet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jacal_db

networks:
  jacalnet: